eksctl create cluster \
--name capstone-ica \
--version 1.17 \
--nodegroup-name standard-workers \
--node-type t2.small \
--nodes 2 \
--nodes-min 1 \
--nodes-max 3 \
--node-ami auto \
--region us-east-1 \
--zones us-east-1a \
--zones us-east-1b \
--zones us-east-1c \
--ssh-public-key [your-key-pair.pem]